### ISSUE TITLE
pan and zoom

### ISSUE THREAD

**Issue by espositofulvio** [google/charts#386]
I've tried to use the panandzoombehavior but, apart from having performance issues, it looks to me that it's not possible to pan if the chart is inside a tab as the tab switching takes control. Is there a way to work around this?

**Comment by jamesncl** [comment]
That sounds like a Flutter issue rather than a charts issue. The tab controller is probably winning the "gesture arena", so the chart never sees the pan gesture. The issue is that you have two widgets listening for horizontal drags in the same physical space, so Flutter has to decide which one has priority. There's a bit of info on [how Flutter determines who wins in the docs](https://flutter.dev/docs/development/ui/advanced/gestures#gesture-disambiguation). Sorry, I don't know enough to suggest a work around but hope that helps a bit. My feeling is that having a zoomable chart inside a horizontally scrollable layout is always going to be problematic, so maybe think about a different layout.

**Comment by espositofulvio** [comment]
Hi @jamesncl, thanks for the response. Indeed I think  you're right. I've managed to work around this by having the tab controller switching tabs when swiping, just passing:

`physics: NeverScrollableScrollPhysics()` 

to the TabBarView, which I guess is the only way to do it.
I'll close this as it's actually not related to charts.
