### ISSUE TITLE
Because no versions of charts_flutter match >0.9.0 <0.10.0 and charts_flutter 0.9.0 depends on intl >=0.15.2 <0.17.0, charts_flutter ^0.9.0 requires intl >=0.15.2 <0.17.0.

### ISSUE THREAD

**Issue by CNMathon** [google/charts#566]
## Description
When I run `flutter pub get`, I got this.

Because no versions of charts_flutter match >0.9.0 <0.10.0 and charts_flutter 0.9.0 depends on intl >=0.15.2 <0.17.0, charts_flutter ^0.9.0 requires intl >=0.15.2 <0.17.0.
And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, charts_flutter ^0.9.0 is incompatible with flutter_localizations from sdk.
So, because bee_bdapp depends on both flutter_localizations any from sdk and charts_flutter ^0.9.0, version solving failed.
pub get failed (1; So, because bee_bdapp depends on both flutter_localizations any from sdk and charts_flutter ^0.9.0, version solving failed.)

## Flutter Doctor
[√] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.1.0)
[√] Connected device (1 available)

## Charts_flutter Version
```
charts_flutter: ^0.9.0
```

**Comment by 1291431532** [comment]
make the following changes to the app’s pubspec.yaml file:
```
dependency_overrides:
 intl: '>=0.15.2 <= 0.17.0-nullsafety.2'
```

**Comment by elansys-kc** [comment]
Perhaps I need to downgrade intl somehow as I get

Warning: You are using these overridden dependencies:
! intl 0.16.1

I still get a build failure

../../../flutter/packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));
      ^^^^^^^^^^^^
../../../flutter/packages/flutter_localizations/lib/src/material_localizations.dart:550:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$licenseCount', formatDecimal(licenseCount));
      ^^^^^^^^^^^^
../../../flutter/packages/flutter_localizations/lib/src/material_localizations.dart:659:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$remainingCount', formatDecimal(remainingCount));
      ^^^^^^^^^^^^
Failed to compile application.

**Comment by elansys-kc** [comment]
I found the following enabled the build to continue. I kept it as an override to show a warning during pub get.

dependency_overrides:
#  intl: '>=0.15.2 <= 0.17.0-nullsafety.2'
  intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

**Comment by CNMathon** [comment]
> I found the following enabled the build to continue. I kept it as an override to show a warning during pub get.
> 
> dependency_overrides:
>   intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

I haven't tried this yet, but I think it is a hark way.
I think a better approach would be for Charts to release an update for its dependent versions.

**Comment by ghenry** [comment]
Please release an update :-)

**Comment by LAPPIT** [comment]
Get the same problem as well:

Because charts_flutter 0.9.0 depends on intl >=0.15.2 <0.17.0 and no versions of charts_flutter match >0.9.0 <0.10.0, charts_flutter ^0.9.0 requires intl >=0.15.2 <0.17.0.
So, because minsockerbit depends on both charts_flutter ^0.9.0 and intl ^0.17.0, version solving failed.
pub get failed (1; So, because minsockerbit depends on both charts_flutter ^0.9.0 and intl ^0.17.0, version solving failed.)

Please release an update! Really hope to be able to continue using the package ...

**Comment by hdavidmb** [comment]
Facing same issue. I tried downgrading `intl` to  `intl: ^0.16.0`, but as my app also depends on `flutter_localizations` it needs `intl: ^0.17.0` so I cannot run my app.
I also hope `charts` gets updated to continue using the package.

**Comment by mit-mit** [comment]
Fixed in https://github.com/google/charts/pull/605
